.TH FFF "1" "December 2023" "fff" "User Commands"
.SH "NAME"
fff \- A simple file manager written in bash
.SH "SYNOPSIS"
.B fff
[\fIOPTION\fR]
.SH "DESCRIPTION"
A simple file manager written in bash
.TP
.B -h
opens this manpage
.TP
.B -v
output version information
.TP
.B -p
store file name in a file on open instead of using `FFF_OPENER`.
.SH "USAGE"
.TP
j
scroll down
.TP
k
scroll up
.TP
h
go to parent dir
.TP
l
go to child dir
.TP
g
go to top
.TP
G
go to bottom
.TP
\-
go to previous dir
.TP
~
go to home
.TP
t
go to trash
.TP
:
go to a directory by typing
.TP
[1-9]
bookmarks
.TP
y
mark copy
.TP
m
mark move
.TP
d
mark trash
.TP
s
mark symbolic link
.TP
b
mark bulk rename
.TP
Y
mark all for copy
.TP
M
mark all for move
.TP
D
mark all for trash
.TP
S
mark all for symbolic link
.TP
B
mark all for bulk rename
.TP
p
paste/move/delete/bulk_rename
.TP
c
clear file selections
.TP
x
vie file/dir attributes
.TP
i
display file preview
.TP
n
new file
.TP
N
new dir
.TP
r
rename
.TP
X
toggle executable
.TP
!
open shell in current dir
.TP
/
search
.TP
\\.
toggle hidden files
.TP
R
refresh current dir
.TP
q
exit with `cd` (if enabled)
.TP
C-c
exit without `cd`
.SH "CUSTOMIZATION"
.PP
All customization is done via global variables with should be put
in `.bashrc` or equivalent.
.PP
The following values are the defaults
.TP
FFF_LS_COLORS=1
.TP
FFF_HIDDEN=1
.TP
FFF_COL1=1
directory color
.TP
FFF_COL2=7
status background color
.TP
FFF_COL3=6
selection color
.TP
FFF_COL4=1
cursor color
.TP
FFF_COL5=0
status foreground color
.TP
FFF_OPENER="vi"
.TP
FFF_PREVIEWER="less"
.TP
FFF_STAT_CMD="stat"
.TP
FFF_CD_ON_EXIT=1
.TP
FFF_CD_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/fff/.fff_d"
.TP
FFF_TRASH="${XDG_DATA_HOME:-$HOME/.local/share}/fff/trash"
.TP
FFF_TRASH_CMD="mv"
.TP
FFF_FAV[1-9]=""
.TP
FFF_FILE_FORMAT="%f"
.TP
FFF_MARK_FORMAT="%f*"
.SH "CUSTOMIZING KEYBINDINGS"
.PP
To prevent the user from being unable to quit the program,
the exit key (`q`) is not able to be remapped.
.PP
The following values are the defaults
.TP
FFF_KEY_SCROLL_DOWN="j"
.TP
FFF_KEY_SCROLL_UP="k"
.TP
FFF_KEY_CHILD="l"
.TP
FFF_KEY_PARENT="h"
.TP
FFF_KEY_TO_TOP="g"
.TP
FFF_KEY_TO_BOTTOM="G"
.TP
FFF_KEY_PREVIOUS="-"
.TP
FFF_KEY_GO_HOME="~"
.TP
FFF_KEY_GO_TRASH="t"
.TP
FFF_KEY_GO_DIR=":"
.TP
FFF_KEY_YANK="y"
.TP
FFF_KEY_MOVE="m"
.TP
FFF_KEY_TRASH="d"
.TP
FFF_KEY_LINK="s"
.TP
FFF_KEY_BULK_RENAME="b"
.TP
FFF_KEY_YANK_ALL="Y"
.TP
FFF_KEY_MOVE_ALL="M"
.TP
FFF_KEY_TRASH_ALL="D"
.TP
FFF_KEY_LINK_ALL="S"
.TP
FFF_KEY_BULK_RENAME_ALL="B"
.TP
FFF_KEY_PASTE="p"
.TP
FFF_KEY_CLEAR="c"
.TP
FFF_KEY_ATTRIBUTES="x"
.TP
FFF_KEY_PREVIEW="i"
.TP
FFF_KEY_MKFILE="n"
.TP
FFF_KEY_MKDIR="N"
.TP
FFF_KEY_RENAME="r"
.TP
FFF_KEY_EXECUTABLE="X"
.TP
FFF_KEY_SHELL="!"
.TP
FFF_KEY_SEARCH="/"
.TP
FFF_KEY_HIDDEN="."
.TP
FFF_KEY_REFRESH="R"
.SH "DISABLING KEYBINDINGS"
.PP
FFF_KEY_UP="off"
.SH "AUTHOR"
Modified by cian callaghan <https://github.com/ciancallaghan>
.br
Originally by dylanaraps <https://github.com/dylanaraps>
.SH "SEE ALSO"
.PP
More documentation availe at:
.br
<https://github.com/ciancallaghan/fff>
.br
<https://github.com/dylanaraps/fff>
